import { FaGraduationCap } from "react-icons/fa6";

export const dataTimeline = [
    {
        position: "BEP/CAP Mécanique Auto",
        compagny: "Lycée des métiers Alexandre Denis",
        compagnyLink: "https://lyc-denis-cerny.ac-versailles.fr/" ,
        time: "1991 - 1994",
        adresse: "Cerny (91)",
        work: "Bep Mécanique Auto",
        diplome: "Diplôme obtenu.",
        obtenu: <FaGraduationCap/>,
    },
    {
        position: "Bac Pro Mécanique Auto",
        compagny: "Lycée Professionnel Gaspard Monge",
        compagnyLink: "https://lyc-monge-savigny.ac-versailles.fr/" ,
        time: "1994 - 1997",
        adresse: "Savigny (77)",
        work: "Bac Pro Mécanique Auto",
        diplome: "Diplôme non obtenu.",
        obtenu: "",
    },
    {
        position: "Technicien de contrôle qualité",
        compagny: "Taglio Application",
        compagnyLink: "https://annuaire-entreprises.data.gouv.fr/entreprise/taglio-application-414870113" ,
        time: "2003 - 2010",
        adresse: "5-7-9, 5 Rue Ampere, 91380 CHILLY-MAZARIN",
        work: "Traitement et revêtement des métaux - Traitement de surface et Thermo laquage.",
        diplome: "",
        obtenu: "",
    },
    {
        position: "Magasinier Cariste",
        compagny: "Les Ateliers du got",
        compagnyLink: "https://les-ateliers-du-gout.fr/" ,
        time: "2010 - 2022",
        adresse: " 4 Rte de la Croix du Rat, 16300 Barbezieux-Saint-Hilaire",
        work: "Secteur Agroalimentaire | Produits fabriqués en France pour les professionnels de la restauration et les freezers centers.",
        diplome: "",
        obtenu: "",
    },
    {
        position: "Intégrateur Web, Développeur frontend",
        compagny: "OpenClassrooms",
        compagnyLink: "https://openclassrooms.com" ,
        time: "2023 - 2024",
        adresse: "Aquitaine, France",
        work: "Formation en ligne pour devenir développeur web à plein temps. Reconversion professionnelle pour être développeur web à plein temps.",
        diplome: "Diplôme obtenu.",
        obtenu: <FaGraduationCap/>,
    },
]