import { url } from "inspector";


export const dataProjet = [
    {
      id: "1",
      num: "01",
      image: "/projets/kasa/kasa5.webp",
      images: [
        { id: "1-1", url: "/projets/kasa/kasa1.webp" },
        { id: "1-2", url: "/projets/kasa/kasa2.webp" },
        { id: "1-3", url: "/projets/kasa/kasa3.webp" },
        { id: "1-4", url: "/projets/kasa/kasa4.webp" },
        { id: "1-5", url: "/projets/kasa/kasa5.webp" },
        { id: "1-6", url: "/projets/kasa/kasa6.webp" },
        { id: "1-7", url: "/projets/kasa/kasa7.webp" },
        { id: "1-8", url: "/projets/kasa/kasa8.webp" }
      ],
      title: "Kasa",
      subtitle: "Agence de location immobilière.",
      date: "2023",
      stack: "React, Sass, HTML, Node.js, Figma",
      theme: "Site Vitrine",
      desc: "Kasa est une entreprise de location de logements de vacances qui souhaite se démarquer de ses concurrents. J'ai réalisé une landing page pour leur site web. J'ai utilisé React avec Vite.js pour la partie front-end et Sass pour le style. Ce projet m'a permis de travailler sur React et de découvrir Vite.js, un outil de build rapide pour les projets React. J'ai également utilisé Git pour versionner mon code et GitHub pour héberger mon projet.",
      href: "https://franckick0909.github.io/kasa-react/",
      github: "https://github.com/franckick0909/kasa-react",
    },
    {
      id: "2",
      num: "02",
      image: "/projets/sophieBluel/bluel1.webp",
      images: [
        { id: "2-1", url: "/projets/sophieBluel/bluel1.webp" },
        { id: "2-2", url: "/projets/sophieBluel/bluel2.webp" },
        { id: "2-3", url: "/projets/sophieBluel/bluel3.webp" },
        { id: "2-4", url: "/projets/sophieBluel/bluel4.webp" },
        { id: "2-5", url: "/projets/sophieBluel/bluel5.webp" },
        { id: "2-6", url: "/projets/sophieBluel/bluel6.webp" },
        { id: "2-7", url: "/projets/sophieBluel/bluel7.webp" },
        { id: "2-8", url: "/projets/sophieBluel/bluel8.webp" }
      ],
      title: "Sophie Bluel",
      subtitle: "Portfolio d'architecte d'intérieur",
      date: "2023",
      stack: "React, Sass, HTML, Node.js, Figma, JavaScript",
      theme: "Site Portfolio",
      desc: "Sophie Bluel est un site de portfolio méticuleusement conçu pour une architecte d'intérieur. Le projet est né d'une maquette FIGMA et s'est transformé en une plateforme interactive avec une interface administrateur sécurisée. Le site permet la gestion dynamique des travaux via des modales.",
      href: "",
      github: "https://github.com/franckick0909/Portfolio-architecte-Sophie-Bluel",
    },
    {
      id: "3",
      num: "03",
      image: "/projets/portfolio-v1/port1.webp",
      images: [
        { id: "3-1", url: "/projets/portfolio-v1/port1.webp" },
        { id: "3-2", url: "/projets/portfolio-v1/port2.webp" },
        { id: "3-3", url: "/projets/portfolio-v1/port3.webp" },
        { id: "3-4", url: "/projets/portfolio-v1/port4.webp" },
        { id: "3-5", url: "/projets/portfolio-v1/port5.webp" },
        { id: "3-6", url: "/projets/portfolio-v1/port6.webp" },
        { id: "3-7", url: "/projets/portfolio-v1/port7.webp" },
        { id: "3-8", url: "/projets/portfolio-v1/port8.webp" }
      ],
      title: "Franck-Chapelon",
      subtitle: "Mon Portfolio-v1",
      date: "2024",
      stack: "React, Sass, HTML, Node.js, Figma, Vite.js, Framer-motion",
      theme: "Site Portfolio",
      desc: "Mon premier portfolio mis en ligne avec le framework Vite.js",
      href: "https://franck-chapelon.fr",
      github: "https://github.com/franckick0909/My-Portfolio",
    },
    {
      id: "4",
      num: "04",
      image: "/projets/dbMovie/db2.webp",
      images: [
        { id: "4-1", url: "/projets/dbMovie/db1.webp" },
        { id: "4-2", url: "/projets/dbMovie/db2.webp" },
        { id: "4-3", url: "/projets/dbMovie/db3.webp" },
        { id: "4-4", url: "/projets/dbMovie/db4.webp" },
        { id: "4-5", url: "/projets/dbMovie/db5.webp" },
        { id: "4-6", url: "/projets/dbMovie/db6.webp" },
        { id: "4-7", url: "/projets/dbMovie/db7.webp" },
        { id: "4-8", url: "/projets/dbMovie/db8.webp" }
      ],
      title: "MovieDB",
      subtitle: "Site de recherche de film",
      date: "2023",
      stack: "React, Sass, HTML, Node.js, Figma, Vite.js, API",
      theme: "Site Evènement",
      desc: "Site de recherche de film réalisé avec l'API The Movie Database (TMDb) et le framework Vite.js",
      href: "https://franckick0909.github.io/NetPrime2/",
      github: "https://github.com/franckick0909/NetPrime2",
    },
    {
      id: "5",
      num: "05",
      image: "/projets/food/food1.webp",
      images: [
        { id: "5-1", url: "/projets/food/food1.webp" },
        { id: "5-2", url: "/projets/food/food2.webp" },
        { id: "5-3", url: "/projets/food/food3.webp" },
        { id: "5-4", url: "/projets/food/food4.webp" },
        { id: "5-5", url: "/projets/food/food5.webp" },
        { id: "5-6", url: "/projets/food/food6.webp" },
        { id: "5-7", url: "/projets/food/food7.webp" },
        { id: "5-8", url: "/projets/food/food8.webp" }
      ],
      title: "OhMyFood",
      subtitle: "Site de réservation de plats en ligne",
      date: "2023",
      stack: "HTML, CSS, Sass, Figma",
      theme: "Site Vitrine",
      desc: "Site de réservation de plats en ligne fictif. L'objectif est d'intégrer la maquette d'un site de foodtech, permettant la commande de repas en ligne réalisé dans le cadre de ma formation chez OpenClassrooms. (projet 4/12)",
      href: "https://franckick0909.github.io/OhMyFood/",
      github: "https://github.com/franckick0909/OhMyFood",
    },
    {
      id: "6",
      num: "06",
      image: "/projets/argentBank/bank5.webp",
      images: [
        { id: "6-1", url: "/projets/argentBank/bank1.webp" },
        { id: "6-2", url: "/projets/argentBank/bank2.webp" },
        { id: "6-3", url: "/projets/argentBank/bank3.webp" },
        { id: "6-4", url: "/projets/argentBank/bank4.webp" },
        { id: "6-5", url: "/projets/argentBank/bank5.webp" },
        { id: "6-6", url: "/projets/argentBank/bank6.webp" },
        { id: "6-7", url: "/projets/argentBank/bank7.webp" },
        { id: "6-8", url: "/projets/argentBank/bank8.webp" }
      ],
      title: "ArgentBank",
      subtitle: "Banque en ligne",
      date: "2024",
      stack: "React, Sass, HTML, Node.js, Figma, Vite.js, Redux, MongoDB, API",
      theme: "Site Entreprise",
      desc: "Argent Bank est un projet que j'ai réalisé dans le cadre de ma formation de Développeur Front-end chez OpenClassrooms. À partir d'une maquette fournie, j'ai développé une application web avec authentification des utilisateurs en utilisant les technologies HTML, CSS, JavaScript, React, React Router, Redux, Sass, une API pour récupérer les données et MongoDB pour stocker les informations des utilisateurs. Le résultat final est une application web sécurisée permettant aux utilisateurs de se connecter à leur compte et de visualiser leurs transactions bancaires. Ce projet m'a permis de renforcer mes compétences en développement front-end et de découvrir l'architecture Redux pour la gestion d'état dans les applications web.",
      href: "",
      github: "https://github.com/franckick0909/Projet-Argent-bank",
    },
  ];