export const dataTarifs = [
    {
        id: 1,
        title: "Site vitrine",
        subtitle: "Standard",
        description: "Site vitrine standard, réalisé avec le framework Next.js",
        couleur: "Selection d'une palette de couleur",
        hebergement: "Nom de domaine + hébergement pendant 12 mois",
        responsive: "Site responsive, adapté à tous les appareils",
        contenu: "Mise en place du contenu textes & images",
        form: "Formulaire de contact",
        reseaux: "Mise en place des réseaux sociaux",
        seo: "Optimisation SEO , référencement naturel",
        onligne: "Mise en ligne du site",
        tarif: "150€/Jour ou à partir de 900€",
        color: "bg-gradient-to-r from-[#fb3a5d] via-[#f97316] to-[#eab308]",
        image: "/img/img1.jpg",
    },
    {
        id: 2,
        title: "Site vitrine",
        subtitle: "Premium, sur mesure",
        description: "Site vitrine premium, réalisé avec le framework Next.js + animations Framer Motion",
        couleur: "Selection d'une palette de couleur",
        hebergement: "Nom de domaine + hébergement pendant 12 mois",
        responsive: "Site responsive, adapté à tous les appareils",
        contenu: "Mise en place du contenu textes & images",
        form: "Formulaire de contact + map Google",
        reseaux: "Mise en place des réseaux sociaux",
        seo: "Optimisation SEO , référencement naturel, SEO sur mesure",
        onligne: "Mise en ligne du site",
        tarif: "150€/Jour ou à partir de 1100€",
        color: "bg-gradient-to-r from-[#fa8cff] via-[#9182ff] to-[#0476ff]",
        image: "/img/img2.jpg",
    },
    {
        id: 3,
        title: "Site e-commerce",
        subtitle: "E-commerce",
        description: "Site e-commerce, réalisé avec le framework Next.js",
        couleur: "Selection d'une palette de couleur",
        hebergement: "Nom de domaine + hébergement pendant 12 mois",
        responsive: "Site responsive, adapté à tous les appareils",
        contenu: "Mise en place du contenu textes & images",
        form: "Formulaire de contact + map + panier",
        reseaux: "Mise en place des réseaux sociaux",
        seo: "Optimisation SEO , référencement naturel, SEO sur mesure",
        onligne: "Mise en ligne du site",
        tarif: "150€/Jour ou à partir de 2000€",
        color: "bg-gradient-to-r from-[#fde047] via-[#fb923c] to-[#f97316]",
        image: "/img/img3.jpg",
    },
    {
        id: 4, 
        title: "Maintenance",
        subtitle: "Mise à jour du site",
        description: "Maintenance du site",
        couleur: "Modifications de la palette de couleur du site",
        hebergement: "Modification d'hébergement pendant 24 mois",
        responsive: "Modifications du site responsive",
        contenu: "Modifications du contenu textes & images",
        form: "Modifications du formulaire de contact",
        reseaux: "Modifications des réseaux sociaux",
        seo: "Modifications de l'optimisation SEO",
        tarif: "50€/Heures",
        color: "bg-[radial-gradient(circle_at_bottom_left,_var(--tw-gradient-stops))] from-[#ff00ff] to-[#00ffff]",
        image: "/img/img3.jpg",
        onligne: "Restauration du site",
    },
]